export const surveyCategories = [
    "Customer Satisfaction",
    "Employee Engagement",
    "Market Research",
    "Product Feedback",
    "Event Feedback",
    "Health and Wellness",
    "Education and Training",
    "Community and Public Opinion",
    "Website Usability",
    "User Experience",
    "Brand Awareness",
    "Advertising Effectiveness",
    "Customer Service Evaluation",
    "Social Media Usage",
    "Political Opinion",
    "Environmental Concerns",
    "Travel Preferences",
    "Food Preferences",
    "Entertainment Preferences",
    "Financial Habits",
    "Technology Usage",
    "Mobile App Feedback",
    "Gaming Habits",
    "Fashion Trends",
  ];